routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontEndController@index')->name('front.index');
Route::get('product/{product}', 'FrontEndController@product')->name('product');
Route::get('products', 'FrontEndController@products')->name('front.products');

Auth::routes();

Route::group(['prefix' => 'seller', 'middleware' => 'auth'], function () {
    Route::post('toggledeliver/{orderId}', 'OrderController@toggledeliver')->name('toggle.deliver');
    Route::get('/', function () {
        return view('admin.index');
    })->name('admin.index');
    Route::post('product/image-upload/{productId}', 'ProductsController@uploadImages');
    Route::resource('product', 'ProductsController');
    Route::resource('category', 'CategoriesController');
    Route::get('orders/{type?}', 'OrderController@Orders');
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('cart', 'ProductsController@cart')->name('cart');
    Route::get('add-to-cart/{id}', 'ProductsController@addToCart');
    Route::patch('update-cart', 'ProductsController@updating');
    Route::delete('remove-from-cart', 'ProductsController@remove');
    Route::resource('review','ProductReviewController');
});

Route::get('wishlist', 'WishlistController@store')->name('addtowishlist');
Route::post('make-order', 'ProductsController@createOrder')->name('make.order');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Http\Filters\Filterable;
use App\Category;
use App\Rating;
use App\User;
use App\Wishlist;

class Product extends Model
{
    use Filterable;

    protected $guarded = [];
    protected $dates = ['ready_date'];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function reviews()
    {
        return $this->hasMany(ProductReview::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
    public function wishlist()
    {
        return $this->hasMany(Wishlist::class);
    }
    public function getStarRating()
    {
        $count = $this->reviews()->count();
        if(empty($count)){
            return 0;
        }
        $starCountSum=$this->reviews()->sum('rating');
        $average=$starCountSum/ $count;

       return $average;

    }

}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Product;
use Darryldecode\Cart\Cart;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ProductsController extends Controller
{
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = auth()->user();
        $products=$users = DB::table('products')->where('user_id', '=',($user->id) )->get();
        return view('admin.product.index',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories=Category::pluck('name','id');
        return view('admin.product.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $formInput=$request->except('image');
        
//        validation
        $this->validate($request,[
            'name'=>'required',
            'Ready_date'=>'required',
            'price'=>'required',
            'image'=>'image|mimes:png,jpg,jpeg|max:10000'
        ]);
//        image upload
        $image=$request->image;
        if($image){
            $imageName=$image->getClientOriginalName();
            $image->move('images',$imageName);
            $formInput['image']=$imageName;
        }
        
        Product::create($formInput);
        return redirect()->route('product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product=Product::find($id);
        $categories=Category::pluck('name','id');
        return view('admin.product.edit',compact(['product','categories']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product=Product::find($id);
        $formInput=$request->except('image');

//        validation
        $this->validate($request,[
            'name'=>'required',
            'ready_date'=>'required',
            'price'=>'required',
            'image'=>'image|mimes:png,jpg,jpeg|max:10000'
        ]);

        //        image upload
        $image=$request->image;
        if($image){
            $imageName=$image->getClientOriginalName();
            $image->move('images',$imageName);
            $formInput['image']=$imageName;
        }

         $product->update($formInput);
        return redirect()->route('product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Product::destroy($id);
        return back();
    }

    public function uploadImages($productId,Request $request)
    {

            
        $product=Product::find($productId);

        //        image upload
        $image=$request->file('file');

        if($image){
            $imageName=time(). $image->getClientOriginalName();
            $image->move('images',$imageName);
            $imagePath= "/img/$imageName";
            $product->images()->create(['image_path'=>$imagePath]);
        }

        return "done";
        // Product::create($formInput);
    }
    public function cart(){
        $cart = session()->get('cart');
        
        return view('cart.index');

    }
    public function addToCart($id){
        
        
        $product = Product::find($id);
 
        if(!$product) {
 
            abort(404);
 
        }
 
        $cart = session()->get('cart');
 
        // if cart is empty then this the first product
        if(!$cart) {
 
            $cart = [
                    $id => [
                        "name" => $product->name,
                        "quantity" => 1,
                        "price" => $product->price,
                        "image" => $product->image
                    ]
            ];
 
            session()->put('cart', $cart);
 
            return redirect()->back()->with('success', 'Product added to cart successfully!');
        }
 
        // if cart not empty then check if this product exist then increment quantity
        if(isset($cart[$id])) {
 
            $cart[$id]['quantity']++;
 
            session()->put('cart', $cart);
 
            return redirect()->back()->with('success', 'Product added to cart successfully!');
 
        }
 
        // if item not exist in cart then add to cart with quantity = 1
        $cart[$id] = [
            "name" => $product->name,
            "quantity" => 1,
            "price" => $product->price,
            "image" => $product->image
        ];
 
        session()->put('cart', $cart);
 
        return redirect()->back()->with('success', 'Product added to cart successfully!');
    }
   
    public function updating(Request $request)
    {
        if($request->id and $request->quantity)
        {
            $cart = session()->get('cart');
 
            $cart[$request->id]["quantity"] = $request->quantity;
 
            session()->put('cart', $cart);
            
 
            session()->flash('Success', 'Cart updated successfully');
        }
    }
 
    public function remove(Request $request)
    {
        if($request->id) {
 
            $cart = session()->get('cart');
 
            if(isset($cart[$request->id])) {
 
                unset($cart[$request->id]);
 
                session()->put('cart', $cart);
            }
 
            session()->flash('Success', 'Product removed successfully');
        }
        
    }

    public static function createOrder(Request $request) {
        $user = auth()->user();
        $order = $user->orders()->create([
            'total_price' => $request->total
        ]);

        $cartItems = session()->get('cart');
        foreach ($cartItems as $productId => $cartItem) {
            $order->orderItems()->attach($productId, [
                'quantity'=> $cartItem['quantity'],
                'total'=> $cartItem['quantity'] * $cartItem['price']
            ]);
        }

        // TODO: Delete cart array from session

        return response()->json("Success", 201);
  }
}

resources/views/admin/product/create.blade.php
@extends('admin.layout.admin')

@section('content')

    <h3>Add Product</h3>

    <div class="row d-flex justify-content-center">
        <div class="col-md-8 col-md-offset-2 ">
            {!! Form::open(['route' => 'product.store', 'method' => 'POST', 'files' => true, 'data-parsley-validate'=>'']) !!}

            <div class="form-group">
                {{ Form::label('name', 'Name') }}
                {{ Form::text('name', null, array('class' => 'form-control','required'=>'','minlength'=>'5')) }}
            </div>
            <div class="form-group">
                {{ Form::label('description', 'Description') }}
                {{ Form::text('description', null, array('class' => 'form-control')) }}
            </div>
            
            <div class="form-group">
                {{ Form::label('price', 'Price in ksh per kg') }}
                {{ Form::text('price', null, array('class' => 'form-control')) }}
            </div>
            <div class="form-group">
                {{ Form::label('quantity', 'Quantity in kgs') }}
                {{ Form::text('quantity', null, array('class' => 'form-control')) }}
            </div>
            <div class="form-group">
                {{ Form::label('Ready_date', 'Ready_date') }}
                {{ Form::date('Ready_date', null, array('class' => 'form-control')) }}
            </div>
            <div class="form-group">
                
                {{ Form::hidden('user_id',  Auth::user()->id )}}
            </div>
            <div class="form-group">
                {{ Form::label('category_id', 'Categories') }}
                {{ Form::select('category_id', $categories, null, ['class' => 'form-control','placeholder'=>'Select Category']) }}
            </div>

            <div class="form-group">
                {{ Form::label('image', 'Image') }}
                {{ Form::file('image',array('class' => 'form-control')) }}
            </div>
            {{ Form::submit('Submit', array('class' => 'btn btn-default')) }}
            {!! Form::close() !!}

        </div>
    </div>



@endsection

resources/views/admin/product/edit.blade.php
@extends('admin.layout.admin')

@section('content')

    <h3>Edit Product</h3>
   <div class="row justify-content-center">
        <div class="col-md-8 col-md-offset-2">
            {!! Form::model($product,['route' => ['product.update',$product->id], 'method' => 'PUT', 'files' => true]) !!}
            <div class="form-group">
                {{ Form::label('name', 'Name') }}
                {{ Form::text('name', null, array('class' => 'form-control','required'=>'','minlength'=>'5')) }}
            </div>

            <div class="form-group">
                {{ Form::label('ready_date', 'ready_date') }}
                {{ Form::date('ready_date', null, array('class' => 'form-control')) }}
            </div>
            <div class="form-group">
                {{ Form::label('price', 'Price') }}
                {{ Form::text('price', null, array('class' => 'form-control')) }}
            </div>
            <div class="form-group">
                {{ Form::label('quantity', 'Quantity') }}
                {{ Form::text('quantity', null, array('class' => 'form-control')) }}
            </div>

            <div class="form-group">
                {{ Form::label('image', 'Image') }}
                {{ Form::file('image',array('class' => 'form-control')) }}
            </div>

             {{ Form::submit('Edit', array('class' => 'btn btn-default')) }}
            {!! Form::close() !!}


        </div>
    </div>



@endsection

resources/views/admin/product/index.blade.php
@extends('admin.layout.admin')

@section('content')

    <h3>Products</h3>

<ul class="container">
    @forelse($products as $product)
    <li class="row">


       <div class="col-md-8">
        <h4>{{$product->name}}</h4>
        
        @foreach($products as $product)
          
          <img src="{{asset('img/' . $product->image)}}" style="max-width: 100px">
  
        @endforeach
        <div>
      <a href="{{route('product.edit',$product->id)}}" class="btn btn-primary btn-sm ">Edit Product</a>
      <br>

        <form action="{{route('product.destroy',$product->id)}}"  method="POST">
           {{csrf_field()}}
           {{method_field('DELETE')}}
           <input class="btn btn-sm btn-danger" type="submit" value="Delete">
         </form>
</div>

         <!--
         <div class="col-md-4">
            
            <form action="/admin/product/image-upload/{{$product->id}}" method="POST" class="dropzone" id="my-awesome-dropzone-{{$product->id}}">
              {{csrf_field()}}

             </form>

        </div>
-->

    </li>

        @empty

        <p>No products<p>

    @endforelse
</ul>


@endsection