routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontEndController@index')->name('front.index');
Route::get('product/{product}', 'FrontEndController@product')->name('product');
Route::get('products', 'FrontEndController@products')->name('front.products');

Auth::routes();

Route::group(['prefix' => 'seller', 'middleware' => 'auth'], function () {
    Route::post('toggledeliver/{orderId}', 'OrderController@toggledeliver')->name('toggle.deliver');
    Route::get('/', function () {
        return view('admin.index');
    })->name('admin.index');
    Route::post('product/image-upload/{productId}', 'ProductsController@uploadImages');
    Route::resource('product', 'ProductsController');
    Route::resource('category', 'CategoriesController');
    Route::get('orders/{type?}', 'OrderController@Orders');
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('cart', 'ProductsController@cart')->name('cart');
    Route::get('add-to-cart/{id}', 'ProductsController@addToCart');
    Route::patch('update-cart', 'ProductsController@updating');
    Route::delete('remove-from-cart', 'ProductsController@remove');
    Route::resource('review','ProductReviewController');
});

Route::get('wishlist', 'WishlistController@store')->name('addtowishlist');
Route::post('make-order', 'ProductsController@createOrder')->name('make.order');

resources/views/admin/layout/includes/header.blade.php
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="index.html">Onfarm</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
	          <li class="nav-item active"><a href="index.html" class="nav-link">Home</a></li>
	          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Shop</a>
              <div class="dropdown-menu" aria-labelledby="dropdown04">
              	<a class="dropdown-item" href="">Shop</a>
              	<a class="dropdown-item" href="">Wishlist</a>
                <a class="dropdown-item" href="">Cart</a>
                
              </div>
            </li>
	          <li class="nav-item"><a href="" class="nav-link">About</a></li>
	          <li class="nav-item"><a href="" class="nav-link">Blog</a></li>
	          <li class="nav-item"><a href="" class="nav-link">Contact</a></li>
	          <li class="nav-item cta cta-colored"><a href="" class="nav-link"><span class="icon-shopping_cart"></span>[0]</a></li>
			  <li class="nav-item cta cta-colored"><a href="" class="nav-link"><span class="icon-person"></span>[Onfarm]</a></li>
	        </ul>
	      </div>
	    </div>
	  </nav>

resources/views/admin/layout/includes/sidenav.blade.php
{{-- Side Navigation --}}
<div class="col-md-2" style="display: block; background colour: blue;">
    <div class="sidebar content-box" style="display: block; background colour: blue;">
        <ul class="nav">
            <!-- Main menu -->
            <li class="current"><a href="{{route('admin.index')}}"><i class="glyphicon glyphicon-home"></i>
                    Dashboard</a></li>
            <li class="submenu">
                <a href="#">
                    <i class="glyphicon glyphicon-list"></i> Products
                    <span class="caret pull-right"></span>
                </a>
                <!-- Sub menu -->
                <ul>
                    <li><a href="{{route('product.index')}}">Products</a></li>
                    <li><a href="{{route('product.create')}}">Add Product</a></li>
                </ul>
            </li>
           
            <li class="submenu">
                <a href="#">
                    <i class="glyphicon glyphicon-list"></i> Orders
                    <span class="caret pull-right"></span>
                </a>
                <!-- Sub menu -->
                <ul>
                    <li><a href="{{url('seller/orders/pending')}}">Pending Orders</a></li>
                    <li><a href="{{url('seller/orders/delivered')}}">Delivered Orders</a></li>
                    <li><a href="{{url('seller/orders')}}">All Orders</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div> <!-- ADMIN SIDE NAV-->